addpatch: web-ext
felixonmars/archriscv-packages pull request #2360
Opened 2023-03-21 01:38 UTC by kxxt

- Disable V8's buggy JIT that makes eslint and babel fail <https://github.com/babel/babel/issues/15501>
  - Upstream bug report: https://bugs.chromium.org/p/v8/issues/detail?id=13836
- Increase test timeout

2023-03-21 02:24 UTC, Xeonacid requested changes

2023-03-21 02:24 UTC, Xeonacid commented on web-ext/riscv64.patch
> ++	"web-ext-no-jit.patch")
```suggestion
+        "nodejs19.diff"
+        "web-ext-no-jit.patch")
```

2023-03-21 02:32 UTC, Xeonacid approved these changes

2023-03-21 22:19 UTC, merged

2023-10-01 06:53 UTC, yan12125 commented
> Increase test timeout

FWIW, I incorporated this change into official PKGBUILD https://gitlab.archlinux.org/archlinux/packaging/packages/web-ext/-/blob/ce832fe576d14ae2e46bc8e20c7c222f42f89042/PKGBUILD#L48

> Disable V8's buggy JIT that makes eslint and babel fail https://github.com/babel/babel/issues/15501

This change is dropped in https://github.com/felixonmars/archriscv-packages/pull/2465

2023-10-01 06:59 UTC, kxxt commented
> FWIW, I incorporated this change into official PKGBUILD https://gitlab.archlinux.org/archlinux/packaging/packages/web-ext/-/blob/ce832fe576d14ae2e46bc8e20c7c222f42f89042/PKGBUILD#L48

Thanks very much!

2024-01-07 04:14 UTC, yan12125 commented
web-ext 7.9.0-1 is now in [extra] and RISC-V patches failed as it's already applied: https://archriscv.felixc.at/.status/log.htm?url=logs/web-ext/web-ext-7.9.0-1.log

2024-01-07 08:05 UTC, Xunop commented
> web-ext 7.9.0-1 is now in [extra] and RISC-V patches failed as it's already applied: https://archriscv.felixc.at/.status/log.htm?url=logs/web-ext/web-ext-7.9.0-1.log

I have removed this patch: https://github.com/felixonmars/archriscv-packages/pull/3414

Thank you for your attention.

2024-01-07 08:54 UTC, yan12125 commented
Thanks!