addpkg: startup-notification
felixonmars/archriscv-packages pull request #2720
Opened 2023-06-10 10:37 UTC by TinySnow

Fixed `config.guess`.

upstream url: https://gitlab.freedesktop.org/xdg/startup-notification/-/issues/5.

2023-06-10 10:43 UTC, Xeonacid requested changes
The patch check is failing...

2023-06-11 14:15 UTC, TinySnow commented
> The patch check is failing...

`asp` pulled the old version, that's the reason why check failed. I'll modify the patch, at the same time, apply to fix the half-automatic script in `wiki` to `pkgctl` in some days. Please give me some time.

2023-06-17 03:46 UTC, Xeonacid approved these changes

2023-06-17 03:47 UTC, TinySnow commented
> The patch check is failing...

The new patch test passed.

2023-06-17 03:49 UTC, merged