addpkg: libredefender
felixonmars/archriscv-packages pull request #384
Opened 2021-11-19 15:59 UTC by Ast-x64

2021-11-19 16:34 UTC, r-value requested changes

2021-11-19 16:34 UTC, r-value commented on libredefender/riscv64.patch
> ++  cargo fetch --locked --target "riscv64gc-unknown-linux-gnu"
I don't think it's a good idea to substitute the variables with specific values, which reduces the generality of `PKGBUILD`.

2021-11-19 16:34 UTC, r-value commented on libredefender/riscv64.patch
> ++  patch -Np1 -i "${srcdir}/fix_ptrace_enum.patch"
`nix-0.23.0`is available and compatible with RISC-V, please remove the patch and bump the dependency instead.

2021-11-19 16:34 UTC, r-value commented on libredefender/fix_type.patch
> ++fn map_scan_result(result: cl_error_t, virname: *const u8) -> Result<ScanResult, ClamError> {
Are these changes compatible with x86_64? I really don't think that it's the source of the problem, could you please explain the reasons for this patch further?

2022-03-29 22:28 UTC, r-value commented
Any updates?

2024-09-16 01:47 UTC, closed without merging

2024-09-16 01:47 UTC, Xeonacid commented
Superseded by #2895 , closing.